### ISSUE TITLE
Incomplete framebuffer in tressfx demo

### ISSUE THREAD

**Issue by Neill3d** [vlj/YAGF#1]
I was trying to run a tressfx demo and on startup I have a message about incomplete framebuffer.
File - Common.cpp, line 303
 HairSMFBO = new GLRTTSet({ HairShadowMapTexture }, HairShadowMapDepth, 640, 640);
Internaly GLRTTSet uses stencil depth format, but hair shadow map depth is depth_component_32f only.
 I've changed this line glTexStorage2D(GL_TEXTURE_2D, 1, GL_DEPTH_COMPONENT32F, 640, 640);
into this one - glTexImage2D(GL_TEXTURE_2D, 0, GL_DEPTH24_STENCIL8, 640, 480, 0, GL_DEPTH_STENCIL, GL_UNSIGNED_INT_24_8, NULL);
 And that helps.

**Comment by vlj** [comment]
Thank for reporting, what is you video card ? I don't know which brand supports what in depth stencil format.

**Comment by Neill3d** [comment]
I have GF 690 GTX, and finaly I couldn't run a demo. Something with hair shadows shader, I will try to figure out.

**Comment by vlj** [comment]
I dropped OpenGL codepath in favor of a Vulkan one.
