### ISSUE TITLE
Current master build errors

### ISSUE THREAD

**Issue by susnux** [vlj/YAGF#5]
In current master there are some build errors, first a simple cmake error (it is just needed to remove meshscenenode.cpp from cmake file):

> CMake Error at CMakeLists.txt:118 (add_executable):
>   Cannot find source file:
> 
> examples/Scene/meshscenenode.cpp
> 
> Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
>   .hxx .in .txx

And then this error:

> [  5%] Building CXX object CMakeFiles/YAGF.dir/src/fullscreen.cpp.o
> In file included from /tmp/YAGF/include/Scene/RenderTargets.h:7:0,
>                  from /tmp/YAGF/include/Scene/FullscreenPass.h:7,
>                  from /tmp/YAGF/src/fullscreen.cpp:3:
> /tmp/YAGF/include/API/GfxApi.h:8:28: fatal error: ..\Core\SColor.h: No such file or directory
>  #include "..\Core\SColor.h"
>                             ^
> compilation terminated.
> In file included from /tmp/YAGF/include/Scene/RenderTargets.h:7:0,
>                  from /tmp/YAGF/src/rendertargets.cpp:3:
> /tmp/YAGF/include/API/GfxApi.h:8:28: fatal error: ..\Core\SColor.h: No such file or directory
>  #include "..\Core\SColor.h"
>                             ^
> compilation terminated.

Full configuration:

> -- Found GLEW: /usr/include  
> -- Found Freetype: /usr/lib64/libfreetype.so (found version "2.5.5") 
> -- Found OpenGL: /usr/lib64/libGL.so  
> -- Try OpenMP C flag = [-fopenmp]
> -- Performing Test OpenMP_FLAG_DETECTED
> -- Performing Test OpenMP_FLAG_DETECTED - Success
> -- Try OpenMP CXX flag = [-fopenmp]
> -- Performing Test OpenMP_FLAG_DETECTED
> -- Performing Test OpenMP_FLAG_DETECTED - Success
> -- Found OpenMP: -fopenmp

**Comment by vlj** [comment]
I cleaned all cmake files, should work now.
